export const ADD_PLACE = 'ADD_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';
export const SHARE_PLACE = 'SHARE_PLACE';
export const  SELECT_PLACE = 'SELECT_PLACE';
export const  UNSELECT_PLACE = 'UNSELECT_PLACE';
export const USERNAME_CHANGED = 'USERNAME_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER = 'LOGIN_USER';
export const SHOW_LOADING = 'SHOW_LOADING';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const EMAIL_CHANGED ='EMAIL_CHANGED';
export const CLEAR_LOGIN_RECORD = 'CLEAR_LOGIN_RECORD'
export const SHOW_LOADING_FORGOT_PASSWORD = 'SHOW_LOADING_FORGOT_PASSWORD'
export const CLEAR_FORGOT_RESPONSE_RECORD = 'CLEAR_FORGOT_RESPONSE_RECORD'
export const REGISTER_USER = 'REGISTER_USER'
export const CLEAR_REGISTRATION_RECORD = 'CLEAR_REGISTRATION_RECORD'
export const SHOW_LOADING_REGISTRATION = 'SHOW_LOADING_REGISTRATION'
export const PHONE_CHANGED = 'PHONE_CHANGED';
export const USER_PROFILE = 'USER_PROFILE';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const SHOW_UPDATE_PROFILE_LOADING = 'SHOW_UPDATE_PROFILE_LOADING';
export const SHOW_PROFILE_LOADING = 'SHOW_PROFILE_LOADING';
export const SHOW_UPDATE_PASSWORD_LOADING = 'SHOW_UPDATE_PASSWORD_LOADING';
export const PHONE_NUM_CHANGED = 'PHONE_NUM_CHANGED';
export const RECEIVE_OTP = 'RECEIVE_OTP';
export const SHOW_OTP_LOADING = 'SHOW_OTP_LOADING';
export const VERIFY_OTP = 'VERIFY_OTP';
export const SHOW_VERIFY_OTP_LOADING = 'SHOW_VERIFY_OTP_LOADING';
export const RESEND_OTP = 'RESEND_OTP';
export const CLEAR_VERIFY_OTP_DATA = 'CLEAR_VERIFY_OTP_DATA';
export const CLEAR_RECEIVE_OTP_DATA = 'CLEAR_RECEIVE_OTP_DATA';
export const DASHBOARD_API = 'DASHBOARD_API';
export const SHOW_DASHBOARD_LOADING = 'SHOW_DASHBOARD_LOADING';
export const DRIVER_STATUS = 'DRIVER_STATUS';
export const SHOW_DRIVER_STATUS_LOADING = 'SHOW_DRIVER_STATUS_LOADING';
export const CLEAR_DRIVER_STATUS_RESPONSE = 'CLEAR_DRIVER_STATUS_RESPONSE';
export const CLEAR_DRIVER_STATUS = 'CLEAR_DRIVER_STATUS';
export const ADDRESS_LIST = 'ADDRESS_LIST';
export const SHOW_ADDRESS_LOADING = 'SHOW_ADDRESS_LOADING';
export const CLEAR_ADDRESS_RECORD = 'CLEAR_ADDRESS_RECORD';
export const DELETE_ADDRESS_RECORD = 'DELETE_ADDRESS_RECORD';
export const SHOW_SAVE_ADDRESS_LOADING = 'SHOW_SAVE_ADDRESS_LOADING';
export const SAVE_ADDRESS = 'SAVE_ADDRESS';
export const CLEAR_SAVE_ADDRESS_RECORD = 'CLEAR_SAVE_ADDRESS_RECORD';
export const CLEAR_DELETE_ADDRESS_RECORD = 'CLEAR_DELETE_ADDRESS_RECORD';
export const CLEAR_LIST_DATA_RECORD = 'CLEAR_LIST_DATA_RECORD';
export const ORDER_DELIVERED_API = 'ORDER_DELIVERED_API';
export const SHOW_ORDER_DELIVER_LOADING = 'SHOW_ORDER_DELIVER_LOADING';


















