export const ADD_PLACE = 'ADD_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';
export const SHARE_PLACE = 'SHARE_PLACE';
export const  SELECT_PLACE = 'SELECT_PLACE';
export const  UNSELECT_PLACE = 'UNSELECT_PLACE';
export const USERNAME_CHANGED = 'USERNAME_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER = 'LOGIN_USER';
export const SHOW_LOADING = 'SHOW_LOADING';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const EMAIL_CHANGED ='EMAIL_CHANGED';
export const CLEAR_LOGIN_RECORD = 'CLEAR_LOGIN_RECORD'
export const SHOW_LOADING_FORGOT_PASSWORD = 'SHOW_LOADING_FORGOT_PASSWORD'
export const CLEAR_FORGOT_RESPONSE_RECORD = 'CLEAR_FORGOT_RESPONSE_RECORD'
export const REGISTER_USER = 'REGISTER_USER'
export const CLEAR_REGISTRATION_RECORD = 'CLEAR_REGISTRATION_RECORD'
export const SHOW_LOADING_REGISTRATION = 'SHOW_LOADING_REGISTRATION'
export const PHONE_CHANGED = 'PHONE_CHANGED';






